name: Continuous Training

on:
  push:
    branches:
      - workflow_continuos_training
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT

jobs:
  continuous-training:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v2  # Use a fixed version

      # Setup Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2  # Use a fixed version
        with:
          python-version: ${{ matrix.python-version }}

      # Install Python dependencies
      - name: Install requirements
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          deactivate

      # Train the model
      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          source venv/bin/activate
          python utilities/setter.py
          export GOOGLE_APPLICATION_CREDENTIALS=path.json  # Make sure this is the correct location
          dvc pull model/model.pkl.dvc -r model-tracker
          dvc unprotect model/model.pkl
          dvc repro -f 
          echo "Training Completed"
          dvc add model/model.pkl -r model-tracker --to-remote
          dvc push model/model.pkl.dvc -r model-tracker
          deactivate

      # Commit and push DVC changes
      - name: Commit .dvc file changes
        run: |
          git config --local user.email "giocrisrai@gmail.com"
          git config --local user.name "giocrisrai"
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization by GitHub Actions"

      # Push changes using GITHUB_TOKEN
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # Use a fixed version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
          branch: ${{ github.ref }}

      # Setup and push metrics
      - uses: iterative/setup-cml@v1
      - name: Push metrics
        run: |
          source venv/bin/activate
          cml-publish reports/prediction_behaviour.png --md >> reports/report.md
          cml-send-comment reports/report.md
          deactivate
