name: Continuous Training

on:
  push:
    branches:
      - workflow_continuos_training
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT

jobs:
  continuous-training:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          deactivate

      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          source venv/bin/activate
          python utilities/setter.py
          export GOOGLE_APPLICATION_CREDENTIALS=path.json
          dvc pull model/model.pkl.dvc -r model-tracker
          dvc unprotect model/model.pkl
          dvc repro -f 
          echo "Training Completed"
          dvc add model/model.pkl -r model-tracker --to-remote
          dvc push model/model.pkl.dvc -r model-tracker
          deactivate

      - name: Commit .dvc file changes
        run: |
          git config --local user.email "giocrisrai@gmail.com"
          git config --local user.name "giocrisrai"
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization by GitHub Actions"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Convert TXT to MD
        run: cp report.txt report.md

      - uses: iterative/setup-cml@v1
      - name: Push metrics
        run: |
          source venv/bin/activate
          cml-publish prediction_behaviour.png --md >> report.md
          cml-send-comment report.md
          deactivate
