name: Continuos Training

on:
  push:
    branches:
      - workflow_continuos_training
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: runing CT

jobs:
  continuos-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python environment
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Set up environment for DVC
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive,gs]

      - name: Setup GCP Credentials
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > sa_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=sa_key.json

      # Test direct GCS access to ensure there are no connection issues
      - name: Test GCS access with gsutil
        run: gsutil ls gs://your-bucket-name/

      - name: Setup DVC remote
        run: |
          dvc remote modify model-tracker credentialpath $(pwd)/sa_key.json

      - name: Print DVC Configuration (for debugging)
        run: |
          dvc remote list
          dvc remote show model-tracker

      - name: Pull model data with verbose logging
        run: |
          dvc pull model/model.pkl.dvc -r model-tracker -v

      - name: Unprotect model
        run: |
          dvc unprotect model/model.pkl

      - name: Train model
        run: |
          dvc repro -f
          echo "Training completed"

      - name: Push new model to remote
        run: |
          dvc add model/model.pkl -r model-tracker --to-remote
          dvc push model/model.pkl.dvc -r model-tracker

      - name: Commit .dvc file changes
        run: |
          git config --local user.email 'giocrisrai@gmail.com'
          git config --local user.name 'Giocrisrai[bot]'
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization"

      - name: Push to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Push metrics
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >> report.md
          cml-publish prediction_behavior.png --md >> report.md
          cml-send-comment report.md

      # Clean up credentials after all steps are finished
      - name: Clean up GCP credentials
        run: rm sa_key.json
